### ISSUE TITLE
打包生成 css存在的问题

### ISSUE THREAD

**Issue by chinbor** [yanyu-fe/vue3-component-demo#3]
## 按照 `packages/ui/vite.config.style.ts` 打包出来的 `css.js` 文件引入存在问题

`css.js`：

![image](https://user-images.githubusercontent.com/35005731/180976694-91628d80-594f-4639-9a69-4faefb906905.png)

`src/button/style/index.ts`：

![image](https://user-images.githubusercontent.com/35005731/180976920-95a95fdf-0bb4-4ea3-8874-7a2e983453d0.png)

**Comment by zuowendong** [comment]
同问，好像是generateBundle中bundler.code生成的值就和源文件不一致，咋修改呀
